# Form implementation generated from reading ui file 'UI/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 662)
        MainWindow.setStyleSheet("#centralwidget{\n"
"    background-color: #F0F0F0;\n"
"}\n"
"\n"
"QPushButton{\n"
"  background-color: #333333;\n"
"  border: none;\n"
"  border-radius: 6px;\n"
"  color: #cccccc;\n"
"  font-size: 14px;\n"
"  font-weight: 500;\n"
"  line-height: 20px;\n"
"  list-style: none;\n"
"  padding: 4px 12px;\n"
"  height:40px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(51, 51, 51, 0.5);\n"
"     text-decoration: none;\n"
"}\n"
"QPushButton:focus{\n"
"     outline: 1px transparent;\n"
"}\n"
"QLabel{\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"}\n"
"QGroupBox{\n"
"    font-weight: bold;\n"
"    font-size: 16px;\n"
"    padding:30px 0px 0px 0px;\n"
"    border:none;\n"
"}\n"
"QLineEdit{\n"
"    border:none;\n"
"    padding:4px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QListWidget{\n"
"    border:none;\n"
"    border-radius: 3px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"border: 1px solid #bbb;\n"
"background: white;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0,    x2: 0, y2: 1,\n"
"    stop: 0 #66e, stop: 1 #bbf);\n"
"background: qlineargradient(x1: 0, y1: 0.2, x2: 1, y2: 1,\n"
"    stop: 0 #bbf, stop: 1 #55f);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -2px;\n"
"margin-bottom: -2px;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 4px;\n"
"}\n"
"\n"
"QScrollArea{\n"
"border: none;\n"
"}\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.images = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.images.setMaximumSize(QtCore.QSize(600, 16777215))
        self.images.setWidgetResizable(True)
        self.images.setObjectName("images")
        self.imagesScrollArea = QtWidgets.QWidget()
        self.imagesScrollArea.setGeometry(QtCore.QRect(0, -72, 573, 2063))
        self.imagesScrollArea.setObjectName("imagesScrollArea")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.imagesScrollArea)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageOneFrame = QtWidgets.QFrame(parent=self.imagesScrollArea)
        self.imageOneFrame.setMinimumSize(QtCore.QSize(0, 500))
        self.imageOneFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageOneFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageOneFrame.setObjectName("imageOneFrame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.imageOneFrame)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.imageOneControllers = QtWidgets.QHBoxLayout()
        self.imageOneControllers.setSpacing(27)
        self.imageOneControllers.setObjectName("imageOneControllers")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.imageOneControllers.addItem(spacerItem)
        self.imageOneModeSelect = QtWidgets.QComboBox(parent=self.imageOneFrame)
        self.imageOneModeSelect.setMinimumSize(QtCore.QSize(100, 0))
        self.imageOneModeSelect.setObjectName("imageOneModeSelect")
        self.imageOneModeSelect.addItem("")
        self.imageOneModeSelect.addItem("")
        self.imageOneModeSelect.addItem("")
        self.imageOneModeSelect.addItem("")
        self.imageOneControllers.addWidget(self.imageOneModeSelect)
        self.verticalLayout_11.addLayout(self.imageOneControllers)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imageOneWidget = QtWidgets.QWidget(parent=self.imageOneFrame)
        self.imageOneWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.imageOneWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.imageOneWidget.setObjectName("imageOneWidget")
        self.verticalLayout_3.addWidget(self.imageOneWidget)
        self.imageOneComponentWidget = QtWidgets.QWidget(parent=self.imageOneFrame)
        self.imageOneComponentWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.imageOneComponentWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.imageOneComponentWidget.setObjectName("imageOneComponentWidget")
        self.verticalLayout_3.addWidget(self.imageOneComponentWidget)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.imageOneFrame)
        self.line = QtWidgets.QFrame(parent=self.imagesScrollArea)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.imageTwoFrame = QtWidgets.QFrame(parent=self.imagesScrollArea)
        self.imageTwoFrame.setMinimumSize(QtCore.QSize(0, 500))
        self.imageTwoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageTwoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageTwoFrame.setObjectName("imageTwoFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.imageTwoFrame)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(27)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.imageTwoModeSelect = QtWidgets.QComboBox(parent=self.imageTwoFrame)
        self.imageTwoModeSelect.setMinimumSize(QtCore.QSize(100, 0))
        self.imageTwoModeSelect.setObjectName("imageTwoModeSelect")
        self.imageTwoModeSelect.addItem("")
        self.imageTwoModeSelect.addItem("")
        self.imageTwoModeSelect.addItem("")
        self.imageTwoModeSelect.addItem("")
        self.horizontalLayout_5.addWidget(self.imageTwoModeSelect)
        self.verticalLayout_12.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.imageTwoWidget = QtWidgets.QWidget(parent=self.imageTwoFrame)
        self.imageTwoWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.imageTwoWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.imageTwoWidget.setObjectName("imageTwoWidget")
        self.verticalLayout_4.addWidget(self.imageTwoWidget)
        self.imageTwoComponentWidget = QtWidgets.QWidget(parent=self.imageTwoFrame)
        self.imageTwoComponentWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.imageTwoComponentWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.imageTwoComponentWidget.setObjectName("imageTwoComponentWidget")
        self.verticalLayout_4.addWidget(self.imageTwoComponentWidget)
        self.verticalLayout_12.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addWidget(self.imageTwoFrame)
        self.line_2 = QtWidgets.QFrame(parent=self.imagesScrollArea)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.imageThreeFrame = QtWidgets.QFrame(parent=self.imagesScrollArea)
        self.imageThreeFrame.setMinimumSize(QtCore.QSize(0, 500))
        self.imageThreeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageThreeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageThreeFrame.setObjectName("imageThreeFrame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.imageThreeFrame)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(27)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.imageThreeModeSelect = QtWidgets.QComboBox(parent=self.imageThreeFrame)
        self.imageThreeModeSelect.setMinimumSize(QtCore.QSize(100, 0))
        self.imageThreeModeSelect.setObjectName("imageThreeModeSelect")
        self.imageThreeModeSelect.addItem("")
        self.imageThreeModeSelect.addItem("")
        self.imageThreeModeSelect.addItem("")
        self.imageThreeModeSelect.addItem("")
        self.horizontalLayout_7.addWidget(self.imageThreeModeSelect)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.imageThreeWidget = QtWidgets.QWidget(parent=self.imageThreeFrame)
        self.imageThreeWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.imageThreeWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.imageThreeWidget.setObjectName("imageThreeWidget")
        self.verticalLayout_5.addWidget(self.imageThreeWidget)
        self.imageThreeComponentWidget = QtWidgets.QWidget(parent=self.imageThreeFrame)
        self.imageThreeComponentWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.imageThreeComponentWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.imageThreeComponentWidget.setObjectName("imageThreeComponentWidget")
        self.verticalLayout_5.addWidget(self.imageThreeComponentWidget)
        self.verticalLayout_13.addLayout(self.verticalLayout_5)
        self.verticalLayout_2.addWidget(self.imageThreeFrame)
        self.line_3 = QtWidgets.QFrame(parent=self.imagesScrollArea)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.imageFourFrame = QtWidgets.QFrame(parent=self.imagesScrollArea)
        self.imageFourFrame.setMinimumSize(QtCore.QSize(0, 500))
        self.imageFourFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.imageFourFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.imageFourFrame.setObjectName("imageFourFrame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.imageFourFrame)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(27)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.imageFourModeSelect = QtWidgets.QComboBox(parent=self.imageFourFrame)
        self.imageFourModeSelect.setMinimumSize(QtCore.QSize(100, 0))
        self.imageFourModeSelect.setObjectName("imageFourModeSelect")
        self.imageFourModeSelect.addItem("")
        self.imageFourModeSelect.addItem("")
        self.imageFourModeSelect.addItem("")
        self.imageFourModeSelect.addItem("")
        self.horizontalLayout_9.addWidget(self.imageFourModeSelect)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.imageFourWidget = QtWidgets.QWidget(parent=self.imageFourFrame)
        self.imageFourWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.imageFourWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.imageFourWidget.setObjectName("imageFourWidget")
        self.verticalLayout_6.addWidget(self.imageFourWidget)
        self.imageFourComponentWidget = QtWidgets.QWidget(parent=self.imageFourFrame)
        self.imageFourComponentWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.imageFourComponentWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.imageFourComponentWidget.setObjectName("imageFourComponentWidget")
        self.verticalLayout_6.addWidget(self.imageFourComponentWidget)
        self.verticalLayout_14.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addWidget(self.imageFourFrame)
        self.images.setWidget(self.imagesScrollArea)
        self.horizontalLayout.addWidget(self.images)
        self.controllers = QtWidgets.QFrame(parent=self.centralwidget)
        self.controllers.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.controllers.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.controllers.setObjectName("controllers")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.controllers)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.componentsMixerFrame = QtWidgets.QFrame(parent=self.controllers)
        self.componentsMixerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.componentsMixerFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.componentsMixerFrame.setObjectName("componentsMixerFrame")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.componentsMixerFrame)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.outputChannelFrame = QtWidgets.QHBoxLayout()
        self.outputChannelFrame.setObjectName("outputChannelFrame")
        self.outputSelectLabel = QtWidgets.QLabel(parent=self.componentsMixerFrame)
        self.outputSelectLabel.setObjectName("outputSelectLabel")
        self.outputChannelFrame.addWidget(self.outputSelectLabel)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.outputChannelFrame.addItem(spacerItem4)
        self.convertButton = QtWidgets.QPushButton(parent=self.componentsMixerFrame)
        self.convertButton.setMinimumSize(QtCore.QSize(0, 15))
        self.convertButton.setObjectName("convertButton")
        self.outputChannelFrame.addWidget(self.convertButton)
        self.mixerModeSelect = QtWidgets.QComboBox(parent=self.componentsMixerFrame)
        self.mixerModeSelect.setObjectName("mixerModeSelect")
        self.mixerModeSelect.addItem("")
        self.mixerModeSelect.addItem("")
        self.outputChannelFrame.addWidget(self.mixerModeSelect)
        self.outputSelect = QtWidgets.QComboBox(parent=self.componentsMixerFrame)
        self.outputSelect.setObjectName("outputSelect")
        self.outputSelect.addItem("")
        self.outputSelect.addItem("")
        self.outputChannelFrame.addWidget(self.outputSelect)
        self.verticalLayout_19.addLayout(self.outputChannelFrame)
        self.componentsFrame = QtWidgets.QScrollArea(parent=self.componentsMixerFrame)
        self.componentsFrame.setWidgetResizable(True)
        self.componentsFrame.setObjectName("componentsFrame")
        self.componentsFrameItems = QtWidgets.QWidget()
        self.componentsFrameItems.setGeometry(QtCore.QRect(0, 0, 550, 418))
        self.componentsFrameItems.setObjectName("componentsFrameItems")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.componentsFrameItems)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.componentOneFrame = QtWidgets.QFrame(parent=self.componentsFrameItems)
        self.componentOneFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.componentOneFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.componentOneFrame.setObjectName("componentOneFrame")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.componentOneFrame)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.componentOneRatioFrame = QtWidgets.QHBoxLayout()
        self.componentOneRatioFrame.setObjectName("componentOneRatioFrame")
        self.componentOneLabel = QtWidgets.QLabel(parent=self.componentOneFrame)
        self.componentOneLabel.setObjectName("componentOneLabel")
        self.componentOneRatioFrame.addWidget(self.componentOneLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.componentOneRatioFrame.addItem(spacerItem5)
        self.componentOneRatioSlider = QtWidgets.QSlider(parent=self.componentOneFrame)
        self.componentOneRatioSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.componentOneRatioSlider.setObjectName("componentOneRatioSlider")
        self.componentOneRatioFrame.addWidget(self.componentOneRatioSlider)
        self.componentOneRatioLabel = QtWidgets.QLabel(parent=self.componentOneFrame)
        self.componentOneRatioLabel.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.componentOneRatioLabel.setFont(font)
        self.componentOneRatioLabel.setObjectName("componentOneRatioLabel")
        self.componentOneRatioFrame.addWidget(self.componentOneRatioLabel)
        self.verticalLayout_20.addLayout(self.componentOneRatioFrame)
        self.componentOneModeFrame = QtWidgets.QHBoxLayout()
        self.componentOneModeFrame.setObjectName("componentOneModeFrame")
        self.componentOneRectangularSelect = QtWidgets.QVBoxLayout()
        self.componentOneRectangularSelect.setObjectName("componentOneRectangularSelect")
        self.componentOneRealRadio = QtWidgets.QRadioButton(parent=self.componentOneFrame)
        self.componentOneRealRadio.setObjectName("componentOneRealRadio")
        self.componentOneRectangularSelect.addWidget(self.componentOneRealRadio)
        self.componentOneImaginaryRadio = QtWidgets.QRadioButton(parent=self.componentOneFrame)
        self.componentOneImaginaryRadio.setObjectName("componentOneImaginaryRadio")
        self.componentOneRectangularSelect.addWidget(self.componentOneImaginaryRadio)
        self.componentOneModeFrame.addLayout(self.componentOneRectangularSelect)
        self.componentOnePolarSelect = QtWidgets.QVBoxLayout()
        self.componentOnePolarSelect.setObjectName("componentOnePolarSelect")
        self.componentOneMagnitudeRadio = QtWidgets.QRadioButton(parent=self.componentOneFrame)
        self.componentOneMagnitudeRadio.setObjectName("componentOneMagnitudeRadio")
        self.componentOnePolarSelect.addWidget(self.componentOneMagnitudeRadio)
        self.componentOnePhaseRadio = QtWidgets.QRadioButton(parent=self.componentOneFrame)
        self.componentOnePhaseRadio.setObjectName("componentOnePhaseRadio")
        self.componentOnePolarSelect.addWidget(self.componentOnePhaseRadio)
        self.componentOneModeFrame.addLayout(self.componentOnePolarSelect)
        self.verticalLayout_20.addLayout(self.componentOneModeFrame)
        self.verticalLayout_36.addWidget(self.componentOneFrame)
        self.componentTwoFrame = QtWidgets.QFrame(parent=self.componentsFrameItems)
        self.componentTwoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.componentTwoFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.componentTwoFrame.setObjectName("componentTwoFrame")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.componentTwoFrame)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.componentTwoLabel = QtWidgets.QLabel(parent=self.componentTwoFrame)
        self.componentTwoLabel.setObjectName("componentTwoLabel")
        self.horizontalLayout_17.addWidget(self.componentTwoLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.componentTwoRatioSlider = QtWidgets.QSlider(parent=self.componentTwoFrame)
        self.componentTwoRatioSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.componentTwoRatioSlider.setObjectName("componentTwoRatioSlider")
        self.horizontalLayout_17.addWidget(self.componentTwoRatioSlider)
        self.componentTwoRatioLabel = QtWidgets.QLabel(parent=self.componentTwoFrame)
        self.componentTwoRatioLabel.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.componentTwoRatioLabel.setFont(font)
        self.componentTwoRatioLabel.setObjectName("componentTwoRatioLabel")
        self.horizontalLayout_17.addWidget(self.componentTwoRatioLabel)
        self.verticalLayout_24.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.componentTwoRectangularSelect = QtWidgets.QVBoxLayout()
        self.componentTwoRectangularSelect.setObjectName("componentTwoRectangularSelect")
        self.componentTwoRealRadio = QtWidgets.QRadioButton(parent=self.componentTwoFrame)
        self.componentTwoRealRadio.setObjectName("componentTwoRealRadio")
        self.componentTwoRectangularSelect.addWidget(self.componentTwoRealRadio)
        self.componentTwoImaginaryRadio = QtWidgets.QRadioButton(parent=self.componentTwoFrame)
        self.componentTwoImaginaryRadio.setObjectName("componentTwoImaginaryRadio")
        self.componentTwoRectangularSelect.addWidget(self.componentTwoImaginaryRadio)
        self.horizontalLayout_18.addLayout(self.componentTwoRectangularSelect)
        self.componentTwoPolarSelect = QtWidgets.QVBoxLayout()
        self.componentTwoPolarSelect.setObjectName("componentTwoPolarSelect")
        self.componentTwoMagnitudeRadio = QtWidgets.QRadioButton(parent=self.componentTwoFrame)
        self.componentTwoMagnitudeRadio.setObjectName("componentTwoMagnitudeRadio")
        self.componentTwoPolarSelect.addWidget(self.componentTwoMagnitudeRadio)
        self.componentTwoPhaseRadio = QtWidgets.QRadioButton(parent=self.componentTwoFrame)
        self.componentTwoPhaseRadio.setObjectName("componentTwoPhaseRadio")
        self.componentTwoPolarSelect.addWidget(self.componentTwoPhaseRadio)
        self.horizontalLayout_18.addLayout(self.componentTwoPolarSelect)
        self.verticalLayout_24.addLayout(self.horizontalLayout_18)
        self.verticalLayout_36.addWidget(self.componentTwoFrame)
        self.componentFourFrame = QtWidgets.QFrame(parent=self.componentsFrameItems)
        self.componentFourFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.componentFourFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.componentFourFrame.setObjectName("componentFourFrame")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.componentFourFrame)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.componentThreeRatioFrame_2 = QtWidgets.QHBoxLayout()
        self.componentThreeRatioFrame_2.setObjectName("componentThreeRatioFrame_2")
        self.componentThreeLabel = QtWidgets.QLabel(parent=self.componentFourFrame)
        self.componentThreeLabel.setObjectName("componentThreeLabel")
        self.componentThreeRatioFrame_2.addWidget(self.componentThreeLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.componentThreeRatioFrame_2.addItem(spacerItem7)
        self.componentThreeRatioSlider = QtWidgets.QSlider(parent=self.componentFourFrame)
        self.componentThreeRatioSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.componentThreeRatioSlider.setObjectName("componentThreeRatioSlider")
        self.componentThreeRatioFrame_2.addWidget(self.componentThreeRatioSlider)
        self.componentThreeRatioLabel = QtWidgets.QLabel(parent=self.componentFourFrame)
        self.componentThreeRatioLabel.setMinimumSize(QtCore.QSize(45, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.componentThreeRatioLabel.setFont(font)
        self.componentThreeRatioLabel.setObjectName("componentThreeRatioLabel")
        self.componentThreeRatioFrame_2.addWidget(self.componentThreeRatioLabel)
        self.verticalLayout_28.addLayout(self.componentThreeRatioFrame_2)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.componentThreeRectangularSelect = QtWidgets.QVBoxLayout()
        self.componentThreeRectangularSelect.setObjectName("componentThreeRectangularSelect")
        self.componentThreeRealRadio = QtWidgets.QRadioButton(parent=self.componentFourFrame)
        self.componentThreeRealRadio.setObjectName("componentThreeRealRadio")
        self.componentThreeRectangularSelect.addWidget(self.componentThreeRealRadio)
        self.componentThreeImaginaryRadio = QtWidgets.QRadioButton(parent=self.componentFourFrame)
        self.componentThreeImaginaryRadio.setObjectName("componentThreeImaginaryRadio")
        self.componentThreeRectangularSelect.addWidget(self.componentThreeImaginaryRadio)
        self.horizontalLayout_20.addLayout(self.componentThreeRectangularSelect)
        self.componentThreePolarSelect = QtWidgets.QVBoxLayout()
        self.componentThreePolarSelect.setObjectName("componentThreePolarSelect")
        self.componentThreeMagnitudeRadio = QtWidgets.QRadioButton(parent=self.componentFourFrame)
        self.componentThreeMagnitudeRadio.setObjectName("componentThreeMagnitudeRadio")
        self.componentThreePolarSelect.addWidget(self.componentThreeMagnitudeRadio)
        self.componentThreePhaseRadio = QtWidgets.QRadioButton(parent=self.componentFourFrame)
        self.componentThreePhaseRadio.setObjectName("componentThreePhaseRadio")
        self.componentThreePolarSelect.addWidget(self.componentThreePhaseRadio)
        self.horizontalLayout_20.addLayout(self.componentThreePolarSelect)
        self.verticalLayout_28.addLayout(self.horizontalLayout_20)
        self.verticalLayout_36.addWidget(self.componentFourFrame)
        self.componentThreeFrame = QtWidgets.QFrame(parent=self.componentsFrameItems)
        self.componentThreeFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.componentThreeFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.componentThreeFrame.setObjectName("componentThreeFrame")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.componentThreeFrame)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.componentThreeRatioFrame = QtWidgets.QHBoxLayout()
        self.componentThreeRatioFrame.setObjectName("componentThreeRatioFrame")
        self.componentFourLabel = QtWidgets.QLabel(parent=self.componentThreeFrame)
        self.componentFourLabel.setObjectName("componentFourLabel")
        self.componentThreeRatioFrame.addWidget(self.componentFourLabel)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.componentThreeRatioFrame.addItem(spacerItem8)
        self.componentFourRatioSlider = QtWidgets.QSlider(parent=self.componentThreeFrame)
        self.componentFourRatioSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.componentFourRatioSlider.setObjectName("componentFourRatioSlider")
        self.componentThreeRatioFrame.addWidget(self.componentFourRatioSlider)
        self.componentFourRatioLabel = QtWidgets.QLabel(parent=self.componentThreeFrame)
        self.componentFourRatioLabel.setMinimumSize(QtCore.QSize(45, 0))
        self.componentFourRatioLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.componentFourRatioLabel.setFont(font)
        self.componentFourRatioLabel.setObjectName("componentFourRatioLabel")
        self.componentThreeRatioFrame.addWidget(self.componentFourRatioLabel)
        self.verticalLayout_32.addLayout(self.componentThreeRatioFrame)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.componentFourRectangularSelect = QtWidgets.QVBoxLayout()
        self.componentFourRectangularSelect.setObjectName("componentFourRectangularSelect")
        self.componentFourRealRadio = QtWidgets.QRadioButton(parent=self.componentThreeFrame)
        self.componentFourRealRadio.setObjectName("componentFourRealRadio")
        self.componentFourRectangularSelect.addWidget(self.componentFourRealRadio)
        self.componentFourImaginaryRadio = QtWidgets.QRadioButton(parent=self.componentThreeFrame)
        self.componentFourImaginaryRadio.setObjectName("componentFourImaginaryRadio")
        self.componentFourRectangularSelect.addWidget(self.componentFourImaginaryRadio)
        self.horizontalLayout_22.addLayout(self.componentFourRectangularSelect)
        self.componentFourPolarSelect = QtWidgets.QVBoxLayout()
        self.componentFourPolarSelect.setObjectName("componentFourPolarSelect")
        self.componentFourMagnitudeRadio = QtWidgets.QRadioButton(parent=self.componentThreeFrame)
        self.componentFourMagnitudeRadio.setObjectName("componentFourMagnitudeRadio")
        self.componentFourPolarSelect.addWidget(self.componentFourMagnitudeRadio)
        self.componentFourPhaseRadio = QtWidgets.QRadioButton(parent=self.componentThreeFrame)
        self.componentFourPhaseRadio.setObjectName("componentFourPhaseRadio")
        self.componentFourPolarSelect.addWidget(self.componentFourPhaseRadio)
        self.horizontalLayout_22.addLayout(self.componentFourPolarSelect)
        self.verticalLayout_32.addLayout(self.horizontalLayout_22)
        self.verticalLayout_36.addWidget(self.componentThreeFrame)
        self.componentsFrame.setWidget(self.componentsFrameItems)
        self.verticalLayout_19.addWidget(self.componentsFrame)
        self.verticalLayout.addWidget(self.componentsMixerFrame)
        self.outputFrame = QtWidgets.QFrame(parent=self.controllers)
        self.outputFrame.setMinimumSize(QtCore.QSize(0, 230))
        self.outputFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.outputFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.outputFrame.setObjectName("outputFrame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.outputFrame)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.outputOneLabel = QtWidgets.QLabel(parent=self.outputFrame)
        self.outputOneLabel.setObjectName("outputOneLabel")
        self.verticalLayout_37.addWidget(self.outputOneLabel)
        self.outputOneWidget = QtWidgets.QWidget(parent=self.outputFrame)
        self.outputOneWidget.setMinimumSize(QtCore.QSize(0, 222))
        self.outputOneWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}")
        self.outputOneWidget.setObjectName("outputOneWidget")
        self.verticalLayout_37.addWidget(self.outputOneWidget)
        self.horizontalLayout_23.addLayout(self.verticalLayout_37)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.outputTwoLabel = QtWidgets.QLabel(parent=self.outputFrame)
        self.outputTwoLabel.setObjectName("outputTwoLabel")
        self.verticalLayout_38.addWidget(self.outputTwoLabel)
        self.outputTwoWidget = QtWidgets.QWidget(parent=self.outputFrame)
        self.outputTwoWidget.setMinimumSize(QtCore.QSize(0, 222))
        self.outputTwoWidget.setStyleSheet("QWidget{\n"
"    border:1px solid;\n"
"}\n"
"")
        self.outputTwoWidget.setObjectName("outputTwoWidget")
        self.verticalLayout_38.addWidget(self.outputTwoWidget)
        self.horizontalLayout_23.addLayout(self.verticalLayout_38)
        self.verticalLayout.addWidget(self.outputFrame)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.progressBar = QtWidgets.QProgressBar(parent=self.controllers)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_10.addWidget(self.progressBar)
        spacerItem9 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.stopButton = QtWidgets.QPushButton(parent=self.controllers)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_10.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout.addWidget(self.controllers)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.imageOneModeSelect.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.imageOneModeSelect.setItemText(1, _translate("MainWindow", "Phase"))
        self.imageOneModeSelect.setItemText(2, _translate("MainWindow", "Real"))
        self.imageOneModeSelect.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.imageTwoModeSelect.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.imageTwoModeSelect.setItemText(1, _translate("MainWindow", "Phase"))
        self.imageTwoModeSelect.setItemText(2, _translate("MainWindow", "Real"))
        self.imageTwoModeSelect.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.imageThreeModeSelect.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.imageThreeModeSelect.setItemText(1, _translate("MainWindow", "Phase"))
        self.imageThreeModeSelect.setItemText(2, _translate("MainWindow", "Real"))
        self.imageThreeModeSelect.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.imageFourModeSelect.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.imageFourModeSelect.setItemText(1, _translate("MainWindow", "Phase"))
        self.imageFourModeSelect.setItemText(2, _translate("MainWindow", "Real"))
        self.imageFourModeSelect.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.outputSelectLabel.setText(_translate("MainWindow", "Mixer Output to"))
        self.convertButton.setText(_translate("MainWindow", "Convert"))
        self.mixerModeSelect.setItemText(0, _translate("MainWindow", "Real/Imaginary"))
        self.mixerModeSelect.setItemText(1, _translate("MainWindow", "Magnitude/Phase"))
        self.outputSelect.setItemText(0, _translate("MainWindow", "Output 1"))
        self.outputSelect.setItemText(1, _translate("MainWindow", "OutPut 2"))
        self.componentOneLabel.setText(_translate("MainWindow", "Component 1: "))
        self.componentOneRatioLabel.setText(_translate("MainWindow", "0%"))
        self.componentOneRealRadio.setText(_translate("MainWindow", "Real"))
        self.componentOneImaginaryRadio.setText(_translate("MainWindow", "Imaginary"))
        self.componentOneMagnitudeRadio.setText(_translate("MainWindow", "Magnitude"))
        self.componentOnePhaseRadio.setText(_translate("MainWindow", "Phase"))
        self.componentTwoLabel.setText(_translate("MainWindow", "Component 2: "))
        self.componentTwoRatioLabel.setText(_translate("MainWindow", "0%"))
        self.componentTwoRealRadio.setText(_translate("MainWindow", "Real"))
        self.componentTwoImaginaryRadio.setText(_translate("MainWindow", "Imaginary"))
        self.componentTwoMagnitudeRadio.setText(_translate("MainWindow", "Magnitude"))
        self.componentTwoPhaseRadio.setText(_translate("MainWindow", "Phase"))
        self.componentThreeLabel.setText(_translate("MainWindow", "Component 3: "))
        self.componentThreeRatioLabel.setText(_translate("MainWindow", "0%"))
        self.componentThreeRealRadio.setText(_translate("MainWindow", "Real"))
        self.componentThreeImaginaryRadio.setText(_translate("MainWindow", "Imaginary"))
        self.componentThreeMagnitudeRadio.setText(_translate("MainWindow", "Magnitude"))
        self.componentThreePhaseRadio.setText(_translate("MainWindow", "Phase"))
        self.componentFourLabel.setText(_translate("MainWindow", "Component 4: "))
        self.componentFourRatioLabel.setText(_translate("MainWindow", "0%"))
        self.componentFourRealRadio.setText(_translate("MainWindow", "Real"))
        self.componentFourImaginaryRadio.setText(_translate("MainWindow", "Imaginary"))
        self.componentFourMagnitudeRadio.setText(_translate("MainWindow", "Magnitude"))
        self.componentFourPhaseRadio.setText(_translate("MainWindow", "Phase"))
        self.outputOneLabel.setText(_translate("MainWindow", "Output 1"))
        self.outputTwoLabel.setText(_translate("MainWindow", "Output 2"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
